Repository zulip/python-zulip-api, pull requests merged in 2018-06, with the labels that each got.

#418 beeminder: Check auth_token in `initialize` by idempotent request.
  zulip_bots/zulip_bots/bots/beeminder/beeminder.py
  zulip_bots/zulip_bots/bots/beeminder/fixtures/test_blank_input.json
  zulip_bots/zulip_bots/bots/beeminder/fixtures/test_help_message.json
  zulip_bots/zulip_bots/bots/beeminder/fixtures/test_invalid_when_handle_message.json
  zulip_bots/zulip_bots/bots/beeminder/fixtures/test_invalid_when_initialize.json
  zulip_bots/zulip_bots/bots/beeminder/fixtures/test_syntax_error.json
  zulip_bots/zulip_bots/bots/beeminder/fixtures/test_valid_auth_token.json
  zulip_bots/zulip_bots/bots/beeminder/test_beeminder.py
Labels: size: XL

#421 bots: Add proper error handling for trivia bot.
  zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py
Labels: size: XS

#420 [WIP] Enable pytest as test-runner in API repo (test-bots only so far)
  requirements.txt
  tools/test-bots
Labels: size: L

#422 bots: Improve response at 3 wrong answers in trivia bot.
  zulip_bots/zulip_bots/bots/trivia_quiz/test_trivia_quiz.py
  zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py
Labels: size: XL

#438 api: Implement GET /messages.
  zulip/zulip/__init__.py
  zulip/zulip/examples/get-messages
Labels: size: M

#442 api: Implement PATCH /streams/<stream_id>.
  zulip/zulip/__init__.py
  zulip/zulip/examples/edit-stream
Labels: size: L

#441 api: Implement DELETE /messages/<message_id>.
  zulip/zulip/__init__.py
  zulip/zulip/examples/delete-message
Labels: size: M

#440 api: Implement GET /messages/<message_id>.
  zulip/zulip/__init__.py
  zulip/zulip/examples/get-raw-message
Labels: size: M

#443 Increase test coverage for `tictactoe` bot
  zulip_bots/zulip_bots/bots/tictactoe/test_tictactoe.py
Labels: size: L

#444 api: Implement GET /messages/<message_id>/history.
  zulip/zulip/__init__.py
  zulip/zulip/examples/message-history
Labels: size: M
