Repository zulip/python-zulip-api, pull requests merged in 2018-07, with the labels that each got.

#446 zulip_bots: Fix get_storage request arguments in StateHandler.
  zulip/zulip/__init__.py
  zulip_bots/zulip_bots/lib.py
  zulip_bots/zulip_bots/tests/test_lib.py
Labels: size: S

#429 #122 Get `giphy` bot to 100% test coverage
  zulip_bots/zulip_bots/bots/giphy/test_giphy.py
Labels: size: XS

#427 #122 Get `youtube` bot to 100% test coverage
  zulip_bots/zulip_bots/bots/youtube/fixtures/test_unknown_error.json
  zulip_bots/zulip_bots/bots/youtube/test_youtube.py
Labels: size: M

#412 #357 Add a better way to run standalone bots
  zulip_bots/zulip_bots/finder.py
  zulip_bots/zulip_bots/run.py
  zulip_bots/zulip_bots/tests/test_run.py
Labels: size: L

#449 api: Implement POST /messages/flags.
  zulip/zulip/__init__.py
  zulip/zulip/examples/update-flags
Labels: size: M

#450 api: Implement GET /realm/emoji.
  zulip/zulip/__init__.py
  zulip/zulip/examples/realm-emoji
Labels: size: M

#451 api: Rename update-flags to update-message-flags.
  zulip/zulip/examples/update-message-flags
Labels: size: S

#448 [WIP] Updating Tests for Merels Bot
  zulip_bots/zulip_bots/bots/merels/libraries/game.py
  zulip_bots/zulip_bots/bots/merels/merels.py
  zulip_bots/zulip_bots/bots/merels/test/test_database.py
  zulip_bots/zulip_bots/bots/merels/test/test_game.py
  zulip_bots/zulip_bots/bots/merels/test/test_mechanics.py
  zulip_bots/zulip_bots/bots/merels/test_merels.py
Labels: size: XL

#453 api: Implement PATCH /users/me/subscriptions/muted_topics.
  zulip/zulip/__init__.py
  zulip/zulip/examples/mute-topic
Labels: size: M

#457 api: Implement /users/me/alert_words.
  zulip/zulip/__init__.py
  zulip/zulip/examples/alert-words
Labels: size: L

#455 api: Implement POST /users/me/subscriptions/properties.
  zulip/zulip/__init__.py
Labels: size: S

#454 Fix post requests for JIRA bot
  zulip_bots/zulip_bots/bots/jira/fixtures/test_create.json
  zulip_bots/zulip_bots/bots/jira/fixtures/test_create_error.json
  zulip_bots/zulip_bots/bots/jira/fixtures/test_edit.json
  zulip_bots/zulip_bots/bots/jira/fixtures/test_edit_error.json
  zulip_bots/zulip_bots/bots/jira/jira.py
Labels: size: M

#460 botserver: Add tests for reading config section by bot name.
  zulip_botserver/tests/test_server.py
Labels: size: S
