Repository zulip/python-zulip-api, pull requests merged in 2018-03, with the labels that each got.

#337 [WIP] tools/deploy script for interfacing with the bot server.
  .gitignore
  tools/deploy
Labels: size: XL

#335 bots/giphy: Support bot response to empty message.
  zulip_bots/zulip_bots/bots/giphy/fixtures/test_random.json
  zulip_bots/zulip_bots/bots/giphy/giphy.conf
  zulip_bots/zulip_bots/bots/giphy/giphy.py
  zulip_bots/zulip_bots/bots/giphy/test_giphy.py
Labels: size: L

#341 stack_overflow bot : Add StackOverflow bot.
  zulip_bots/zulip_bots/bots/stack_overflow/__init__.py
  zulip_bots/zulip_bots/bots/stack_overflow/doc.md
  zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_incorrect_query.json
  zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_multi_word.json
  zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_number_query.json
  zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_single_word.json
  zulip_bots/zulip_bots/bots/stack_overflow/fixtures/test_status_code.json
  zulip_bots/zulip_bots/bots/stack_overflow/requirements.txt
  zulip_bots/zulip_bots/bots/stack_overflow/stack_overflow.py
  zulip_bots/zulip_bots/bots/stack_overflow/test_stack_overflow.py
Labels: size: XL

#346 game_handler: Use avatars instead of emails in game handler messages.
  zulip_bots/zulip_bots/bots/game_handler_bot/test_game_handler_bot.py
  zulip_bots/zulip_bots/game_handler.py
Labels: size: M

#342 bots/flock: Add flock bot.
  zulip_bots/zulip_bots/bots/flock/assests/1.png
  zulip_bots/zulip_bots/bots/flock/doc.md
  zulip_bots/zulip_bots/bots/flock/fixtures/test_message_send_failed.json
  zulip_bots/zulip_bots/bots/flock/fixtures/test_message_send_success.json
  zulip_bots/zulip_bots/bots/flock/fixtures/test_no_recipient_found.json
  zulip_bots/zulip_bots/bots/flock/flock.conf
  zulip_bots/zulip_bots/bots/flock/flock.py
  zulip_bots/zulip_bots/bots/flock/requirements.txt
  zulip_bots/zulip_bots/bots/flock/test_flock.py
Labels: size: XL

#352 Add twitpost bot.
  zulip_bots/zulip_bots/bots/twitpost/Readme.md
  zulip_bots/zulip_bots/bots/twitpost/fixtures/api_response.json
  zulip_bots/zulip_bots/bots/twitpost/test_twitpost.py
  zulip_bots/zulip_bots/bots/twitpost/twitpost.py
  zulip_bots/zulip_bots/bots/twitpost/twitter.ini
Labels: size: XL

#349 tools/deploy: Annotate tools/deploy using mypy
  tools/deploy
Labels: size: M

#355 [WIP] Add Trello integration script
  zulip/integrations/trello/README.md
  zulip/integrations/trello/requirements.txt
  zulip/integrations/trello/zulip_trello.py
  zulip/integrations/trello/zulip_trello_config.py
  zulip/integrations/trello/zulip_trello_webhooks.csv
Labels: size: XL

#353 mypy: Support files without extensions for scripts in /tools.
  tools/run-mypy
Labels: size: S

#362 API: Use `session.headers.update` method to add user-agent header.
  zulip/zulip/__init__.py
Labels: size: XS

#365 zulip: Amend default value of remove_subscriptions:principals to None.
  zulip/zulip/__init__.py
Labels: size: XS

#364 mypy: Improve type annotations in Zulip API.
  zulip/zulip/__init__.py
Labels: size: S
