Repository zulip/python-zulip-api, pull requests merged in 2018-05, with the labels that each got.

#376 #338 Add `tools/deploy delete` command.
  tools/deploy
Labels: size: S

#377 #338 deploy: Add `tools/deploy ls` command.
  tools/deploy
Labels: size: L

#379 deploy: Support new JSON-formatted responses from Botfarm.
  tools/deploy
Labels: size: XL

#381 tools/deploy: Read $SERVER and $TOKEN environment variables.
  tools/deploy
Labels: size: M

#59 Dig a tunnel to matrix.
  zulip/integrations/matrix/README.md
  zulip/integrations/matrix/matrix_bridge.py
  zulip/integrations/matrix/matrix_bridge_config.py
Labels: needs review, size: XL

#382 #356 Automatically add a bot handler's parent dir to the python path
  zulip_bots/zulip_bots/run.py
  zulip_bots/zulip_bots/test_run.py
Labels: priority: high, size: M

#386 requirements: Add 'security' extra_require for requests.
  zulip/setup.py
Labels: size: XS

#389 Cleanup and style
  zulip_botserver/tests/server_test_lib.py
  zulip_botserver/tests/test_server.py
  zulip_botserver/zulip_botserver/server.py
Labels: size: XL

#394 zulip-terminal: Add bot's directory to sys.path.
  zulip_bots/zulip_bots/terminal.py
Labels: size: XS

#408 botserver: Validate token before accepting message.
  zulip_botserver/tests/test.conf
  zulip_botserver/tests/test_server.py
  zulip_botserver/zulip_botserver/server.py
Labels: size: M

#410 bot lib tests: Move tests of bot library to tests/.
  tools/run-mypy
  tools/test-lib
  zulip_bots/zulip_bots/tests/test_lib.py
  zulip_bots/zulip_bots/tests/test_run.py
Labels: size: S
