Repository zulip/python-zulip-api, pull requests merged in 2018-08, with the labels that each got.

#465 api: Implement POST /typing.
  zulip/zulip/__init__.py
Labels: size: S

#468 api: Implement GET /server_settings.
  zulip/zulip/__init__.py
Labels: size: S

#467 api: Implement POST /mark_(all|stream|topic)_as_read.
  zulip/zulip/__init__.py
Labels: size: M

#466 api: Implement PATCH /settings/notifications.
  zulip/zulip/__init__.py
Labels: size: S

#473 Quick readability improvement
  README.md
Labels: size: XS

#472 api: Implement DELETE /streams/<stream_id>.
  zulip/zulip/__init__.py
  zulip/zulip/examples/delete-stream
Labels: size: M

#474 api: Implement GET /user_groups.
  zulip/zulip/__init__.py
Labels: size: S

#475 api: Rename "get_presence" to "get_user_presence".
  zulip/zulip/__init__.py
  zulip/zulip/examples/get-user-presence
Labels: size: S
