Repository zulip/python-zulip-api, pull requests merged in 2018-02, with the labels that each got.

#320 Create Dropbox bot to do primary file operations.
  zulip_bots/zulip_bots/bots/dropbox_share/__init__.py
  zulip_bots/zulip_bots/bots/dropbox_share/doc.md
  zulip_bots/zulip_bots/bots/dropbox_share/dropbox_share.conf
  zulip_bots/zulip_bots/bots/dropbox_share/dropbox_share.py
  zulip_bots/zulip_bots/bots/dropbox_share/requirements.txt
  zulip_bots/zulip_bots/bots/dropbox_share/test_dropbox_share.py
  zulip_bots/zulip_bots/bots/dropbox_share/test_util.py
Labels: size: XL

#309 integrated bots: Add Trello Interactive Bot.
  tools/run-mypy
  zulip_bots/zulip_bots/bots/trello/__init__.py
  zulip_bots/zulip_bots/bots/trello/assets/list_commands.png
  zulip_bots/zulip_bots/bots/trello/doc.md
  zulip_bots/zulip_bots/bots/trello/fixtures/exception_boards.json
  zulip_bots/zulip_bots/bots/trello/fixtures/exception_cards.json
  zulip_bots/zulip_bots/bots/trello/fixtures/exception_checklists.json
  zulip_bots/zulip_bots/bots/trello/fixtures/exception_lists.json
  zulip_bots/zulip_bots/bots/trello/fixtures/get_all_boards.json
  zulip_bots/zulip_bots/bots/trello/fixtures/get_board_descs.json
  zulip_bots/zulip_bots/bots/trello/fixtures/get_cards.json
  zulip_bots/zulip_bots/bots/trello/fixtures/get_checklists.json
  zulip_bots/zulip_bots/bots/trello/fixtures/get_lists.json
  zulip_bots/zulip_bots/bots/trello/requirements.txt
  zulip_bots/zulip_bots/bots/trello/test_trello.py
  zulip_bots/zulip_bots/bots/trello/trello.conf
  zulip_bots/zulip_bots/bots/trello/trello.py
Labels: size: XL

#325 Make `game_handler` support starting a game with a range of players.
  zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py
  zulip_bots/zulip_bots/bots/game_handler_bot/test_game_handler_bot.py
  zulip_bots/zulip_bots/game_handler.py
Labels: size: S

#326 tests: Test handling of bad moves in connect four.
  zulip_bots/zulip_bots/bots/connect_four/controller.py
  zulip_bots/zulip_bots/bots/connect_four/test_connect_four.py
Labels: size: M

#327 Susi AI Bot: Create a susi ai bot.
  tools/run-mypy
  zulip_bots/zulip_bots/bots/susi/__init__.py
  zulip_bots/zulip_bots/bots/susi/fixtures/test_reply.json
  zulip_bots/zulip_bots/bots/susi/susi.py
  zulip_bots/zulip_bots/bots/susi/test_susi.py
Labels: size: XL
