Repository zulip/python-zulip-api, pull requests merged in 2019-01, with the labels that each got.

#469 Fix bridge_with_irc
  zulip/integrations/bridge_with_irc/irc-mirror.py
  zulip/integrations/bridge_with_irc/irc_mirror_backend.py
Labels: size: M

#498 bridge_with_irc: Tell people to subscribe their bots to the stream.
  zulip/integrations/bridge_with_irc/README.md
Labels: size: XS

#501 zulip/examples: Add a script to get complete history of a narrow.
  zulip/zulip/examples/get-history
Labels: priority: high, size: L

#502 bots: Make trivia bot responses mention currently interacting user.
  zulip_bots/zulip_bots/bots/trivia_quiz/test_trivia_quiz.py
  zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py
Labels: size: M

#503 bots: Use bold formatting judiciously in trivia bot.
  zulip_bots/zulip_bots/bots/trivia_quiz/test_trivia_quiz.py
  zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py
Labels: size: S
