Repository zulip/python-zulip-api, pull requests merged in 2020-04, with the labels that each got.

#567 bots: Remove unmaintained bots.
  zulip_bots/zulip_bots/bots_unmaintained/README.md
  zulip_bots/zulip_bots/bots_unmaintained/commute/__init__.py
  zulip_bots/zulip_bots/bots_unmaintained/commute/commute.conf
  zulip_bots/zulip_bots/bots_unmaintained/commute/commute.py
  zulip_bots/zulip_bots/bots_unmaintained/commute/doc.md
  zulip_bots/zulip_bots/bots_unmaintained/foursquare/__init__.py
  zulip_bots/zulip_bots/bots_unmaintained/foursquare/doc.md
  zulip_bots/zulip_bots/bots_unmaintained/foursquare/foursquare.conf
  zulip_bots/zulip_bots/bots_unmaintained/foursquare/foursquare.py
  zulip_bots/zulip_bots/bots_unmaintained/howdoi/__init__.py
  zulip_bots/zulip_bots/bots_unmaintained/howdoi/assets/answer_howdoi_all.png
  zulip_bots/zulip_bots/bots_unmaintained/howdoi/assets/answer_howdowe.png
  zulip_bots/zulip_bots/bots_unmaintained/howdoi/assets/question_howdoi_all.png
  zulip_bots/zulip_bots/bots_unmaintained/howdoi/assets/question_howdowe.png
  zulip_bots/zulip_bots/bots_unmaintained/howdoi/doc.md
  zulip_bots/zulip_bots/bots_unmaintained/howdoi/howdoi.py
  zulip_bots/zulip_bots/bots_unmaintained/john/__init__.py
  zulip_bots/zulip_bots/bots_unmaintained/john/assets/assist.png
  zulip_bots/zulip_bots/bots_unmaintained/john/assets/greetings.png
  zulip_bots/zulip_bots/bots_unmaintained/john/assets/joke.png
  zulip_bots/zulip_bots/bots_unmaintained/john/assets/var/jokes.json
  zulip_bots/zulip_bots/bots_unmaintained/john/doc.md
  zulip_bots/zulip_bots/bots_unmaintained/john/john.py
Labels: size: XL

#574 lint: Remove explicit python invocation check.
  tools/custom_check.py
Labels: size: XS

#576 bridges: Remove sender field from message data.
  zulip/integrations/bridge_between_zulips/run-interrealm-bridge
  zulip/integrations/bridge_with_matrix/matrix_bridge.py
Labels: size: XS

#580 minor: Warn about missing usage handlers.
  zulip_bots/zulip_bots/lib.py
Labels: size: XS

#578 zulip/zulip/__init__.py: Remove shebang and add version assertion.
  zulip/zulip/__init__.py
Labels: size: XS

#579 api: Refactor get_user_by_id to take keyword arguments
  zulip/zulip/__init__.py
Labels: size: S

#572 api: Implement DELETE /users/{user_id} api endpoint
  zulip/zulip/__init__.py
Labels: size: S

#547 bridge_between_zulips: Add explanation of --stream to README.md.
  zulip/integrations/bridge_between_zulips/README.md
  zulip/integrations/bridge_between_zulips/run-interrealm-bridge
Labels: size: S

#562 api: Implement GET /attachments endpoint
  zulip/zulip/__init__.py
Labels: size: S

#581 api: Implement GET /realm/presence endpoint.
  zulip/zulip/__init__.py
Labels: size: S

#570 api: Implement PATCH /users/{user_id} endpoint
  zulip/zulip/__init__.py
Labels: size: S

#583 api: Implement POST /users/{user_id}/reactivate endpoint.
  zulip/zulip/__init__.py
Labels: size: S

#550 api: Implement GET /messages/matches_narrow endpoint
  zulip/zulip/__init__.py
Labels: size: S

#584 api: Implement POST /default_streams api endpoint.
  zulip/zulip/__init__.py
Labels: size: S

#589 finder: Remove ModuleNotFoundError handler
  zulip_bots/zulip_bots/finder.py
Labels: size: XS

#554 Bots in Group PMs
  zulip_bots/zulip_bots/lib.py
  zulip_bots/zulip_bots/tests/test_lib.py
Labels: size: M
