Repository zulip/python-zulip-api, pull requests merged in 2020-05, with the labels that each got.

#593 ExternalBotHandler: Support adding reactions to message for a bot..
  zulip_bots/zulip_bots/bots/helloworld/helloworld.py
  zulip_bots/zulip_bots/lib.py
  zulip_bots/zulip_bots/simple_lib.py
  zulip_bots/zulip_bots/test_lib.py
  zulip_bots/zulip_bots/tests/test_lib.py
Labels: size: M

#598 mailmap: Add Git .mailmap for zulipchat.com → zulip.com
  .mailmap
Labels: size: S

#599 api: Add bindings for /realm/profile_fields and /realm/profile_fields/{field_id} api endpoints.
  zulip/zulip/__init__.py
Labels: size: L
