Repository zulip/python-zulip-api, pull requests merged in 2020-08, with the labels that each got.

#606 api: Implement DELETE /realm/emoji/{emoji_name}.
  zulip/zulip/__init__.py
Labels: size: S

#613 Matrix bridge: Change the condition of not_from_zulip_bot.
  zulip/integrations/bridge_with_matrix/matrix_bridge.py
Labels: size: XS

#600 api: Update type annotation in 'remove_subscriptions'.
  zulip/zulip/__init__.py
Labels: size: S

#617 api: Implement GET /users/{user_id}/subscriptions/{stream_id} endpoint.
  zulip/zulip/__init__.py
Labels: size: S

#614 zulip: Add hash_util_decode() to decode server encoded URL excerpts
  zulip/tests/test_hash_util_decode.py
  zulip/zulip/__init__.py
Labels: size: M
