Repository zulip/python-zulip-api, pull requests merged in 2021-03, with the labels that each got.

#660 requirements: Upgrade mypy from 0.790 to 0.812
  requirements.txt
Labels: size: XS

#661 Fix % formatting without a tuple
  zulip/integrations/bridge_with_irc/irc_mirror_backend.py
  zulip/integrations/bridge_with_matrix/matrix_bridge.py
  zulip/integrations/codebase/zulip_codebase_mirror
  zulip/integrations/trac/zulip_trac.py
  zulip/zulip/__init__.py
  zulip/zulip/send.py
  zulip_bots/zulip_bots/bots/giphy/giphy.py
  zulip_bots/zulip_bots/bots/xkcd/xkcd.py
Labels: size: M

#666 zulip: Add support for additional args for call_on_each_*.
  zulip/zulip/__init__.py
Labels: size: S
