Repository zulip/python-zulip-api, pull requests merged in 2021-04, with the labels that each got.

#674 zulip-bots: Fix incrementor to handle edit time limit error.
  zulip_bots/zulip_bots/bots/incrementor/incrementor.py
  zulip_bots/zulip_bots/bots/incrementor/test_incrementor.py
Labels: size: M

#676 sync-public-streams: Rewrite using an event queue
  zulip/integrations/zephyr/sync-public-streams
Labels: size: L

#680 zulip: Fix call_on_each_event.
  zulip/zulip/__init__.py
Labels: size: S

#681 zulip: Replace GET realm/filters with realm/linkifiers.
  zulip/zulip/__init__.py
Labels: size: S
