Repository zulip/python-zulip-api, pull requests merged in 2022-01, with the labels that each got.

#741 tools: Delete the release-packages script.
  tools/release-packages
  zulip_bots/setup.py
Labels: size: XL

#742 tools/provision: Bump required pip version from >=9.0 to >=10.
  tools/provision
Labels: size: XS

#743 zulip: Fix principals default for remove_subscriptions
  zulip/zulip/__init__.py
Labels: size: S
