Repository zulip/python-zulip-api, pull requests merged in 2022-02, with the labels that each got.

#745 converter: Reformat with Black 22
  zulip_bots/zulip_bots/bots/converter/converter.py
Labels: size: XS

#737 api: Add subset of Literal types used in zulip-terminal
  zulip/setup.py
  zulip/zulip/__init__.py
Labels: size: M

#744 Remove legacy distutils support
  zulip/README.md
  zulip/setup.py
  zulip/zulip/__init__.py
  zulip_bots/setup.py
  zulip_botserver/setup.py
Labels: size: XL

#735 zulip: Reraise exceptions in do_api_query.
  zulip/zulip/__init__.py
Labels: size: M
