Repository zulip/python-zulip-api, pull requests merged in 2023-05, with the labels that each got.

#780 Fix recent linter errors
  requirements.txt
  zulip/integrations/git/zulip_git_config.py
  zulip/integrations/openshift/zulip_openshift_config.py
  zulip/integrations/perforce/zulip_perforce_config.py
  zulip/integrations/svn/zulip_svn_config.py
  zulip/integrations/zephyr/check-mirroring
  zulip/integrations/zephyr/zephyr_mirror.py
  zulip/integrations/zephyr/zephyr_mirror_backend.py
  zulip/zulip/__init__.py
  zulip_bots/zulip_bots/bots/define/test_define.py
  zulip_bots/zulip_bots/bots/flock/flock.py
  zulip_bots/zulip_bots/bots/game_of_fifteen/game_of_fifteen.py
  zulip_bots/zulip_bots/bots/incident/incident.py
  zulip_bots/zulip_bots/bots/merels/libraries/game.py
  zulip_bots/zulip_bots/bots/stack_overflow/test_stack_overflow.py
  zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py
  zulip_bots/zulip_bots/bots/weather/test_weather.py
  zulip_bots/zulip_bots/bots/wikipedia/test_wikipedia.py
  zulip_bots/zulip_bots/bots/youtube/youtube.py
  zulip_bots/zulip_bots/lib.py
  zulip_bots/zulip_bots/test_lib.py
  zulip_bots/zulip_bots/tests/test_run.py
Labels: size: L

#782 Remove unnecessary "sender" in request data
  zulip/integrations/rss/rss-bot
Labels: size: XS

#781 Do not send heartbeat events to clients.
  zulip/zulip/__init__.py
Labels: size: S
