Repository zulip/python-zulip-api, pull requests merged in 2023-11, with the labels that each got.

#809 ruff: Reformat with ruff 0.1.4
  requirements.txt
  zulip_bots/zulip_bots/bots/beeminder/beeminder.py
Labels: size: S

#810 ruff: Fix S108 Probable insecure usage of temporary file or directory
  zulip/integrations/codebase/requirements.txt
  zulip/integrations/codebase/zulip_codebase_config.py
  zulip/integrations/log2zulip/log2zulip
  zulip/integrations/log2zulip/requirements.txt
  zulip/integrations/zephyr/zephyr_mirror_backend.py
Labels: size: S

#811 merels: Convert incorrectly shared class variable to instance variable
  zulip_bots/zulip_bots/bots/merels/merels.py
Labels: size: XS

#812 ruff: Enable lots of rules
  pyproject.toml
  tools/deploy
  zulip/integrations/bridge_with_matrix/matrix_bridge.py
  zulip/integrations/google/get-google-credentials
  zulip/integrations/google/google-calendar
  zulip/integrations/rss/rss-bot
  zulip/integrations/zephyr/check-mirroring
  zulip/integrations/zephyr/zephyr_ctypes.py
  zulip/integrations/zephyr/zephyr_mirror_backend.py
  zulip/zulip/__init__.py
  zulip/zulip/examples/upload-file
  zulip_bots/zulip_bots/bots/idonethis/idonethis.py
  zulip_bots/zulip_bots/bots/mention/test_mention.py
  zulip_bots/zulip_bots/bots/tictactoe/tictactoe.py
  zulip_bots/zulip_bots/bots/xkcd/xkcd.py
  zulip_bots/zulip_bots/game_handler.py
  zulip_bots/zulip_bots/lib.py
  zulip_bots/zulip_bots/request_test_lib.py
  zulip_botserver/tests/test_server.py
  zulip_botserver/zulip_botserver/server.py
Labels: size: XL

#793 IRC: Add option for SASL authentication.
  zulip/integrations/bridge_with_irc/irc-mirror.py
  zulip/integrations/bridge_with_irc/irc_mirror_backend.py
  zulip/integrations/bridge_with_irc/requirements.txt
Labels: size: M

#815 IRC: Handle error by displaying the error message.
  zulip/integrations/bridge_with_irc/irc_mirror_backend.py
Labels: size: XS
