Repository zulip/python-zulip-api, pull requests merged in 2024-11, with the labels that each got.

#837 rss-bot: Handle feed entries that lack a `title` field.
  zulip/integrations/rss/rss-bot
Labels: size: XS

#838 bots: Rename BotHandler to AbstractBotHandler.
  packaged_helloworld/packaged_helloworld/packaged_helloworld.py
  zulip_bots/zulip_bots/bots/baremetrics/baremetrics.py
  zulip_bots/zulip_bots/bots/beeminder/beeminder.py
  zulip_bots/zulip_bots/bots/chessbot/chessbot.py
  zulip_bots/zulip_bots/bots/converter/converter.py
  zulip_bots/zulip_bots/bots/define/define.py
  zulip_bots/zulip_bots/bots/dialogflow/dialogflow.py
  zulip_bots/zulip_bots/bots/dropbox_share/dropbox_share.py
  zulip_bots/zulip_bots/bots/encrypt/encrypt.py
  zulip_bots/zulip_bots/bots/file_uploader/file_uploader.py
  zulip_bots/zulip_bots/bots/flock/flock.py
  zulip_bots/zulip_bots/bots/followup/followup.py
  zulip_bots/zulip_bots/bots/front/front.py
  zulip_bots/zulip_bots/bots/giphy/giphy.py
  zulip_bots/zulip_bots/bots/github_detail/github_detail.py
  zulip_bots/zulip_bots/bots/google_search/google_search.py
  zulip_bots/zulip_bots/bots/helloworld/helloworld.py
  zulip_bots/zulip_bots/bots/help/help.py
  zulip_bots/zulip_bots/bots/idonethis/idonethis.py
  zulip_bots/zulip_bots/bots/incident/incident.py
  zulip_bots/zulip_bots/bots/incrementor/incrementor.py
  zulip_bots/zulip_bots/bots/jira/jira.py
  zulip_bots/zulip_bots/bots/link_shortener/link_shortener.py
  zulip_bots/zulip_bots/bots/mention/mention.py
  zulip_bots/zulip_bots/bots/monkeytestit/monkeytestit.py
  zulip_bots/zulip_bots/bots/salesforce/salesforce.py
  zulip_bots/zulip_bots/bots/stack_overflow/stack_overflow.py
  zulip_bots/zulip_bots/bots/susi/susi.py
  zulip_bots/zulip_bots/bots/trello/trello.py
  zulip_bots/zulip_bots/bots/trivia_quiz/trivia_quiz.py
  zulip_bots/zulip_bots/bots/twitpost/twitpost.py
  zulip_bots/zulip_bots/bots/virtual_fs/virtual_fs.py
  zulip_bots/zulip_bots/bots/weather/weather.py
  zulip_bots/zulip_bots/bots/wikipedia/wikipedia.py
  zulip_bots/zulip_bots/bots/witai/witai.py
  zulip_bots/zulip_bots/bots/xkcd/xkcd.py
  zulip_bots/zulip_bots/bots/yoda/yoda.py
  zulip_bots/zulip_bots/bots/youtube/youtube.py
  zulip_bots/zulip_bots/game_handler.py
  zulip_bots/zulip_bots/lib.py
  zulip_bots/zulip_bots/tests/test_lib.py
  zulip_botserver/tests/test_server.py
Labels: size: XL

#840 github: Add a zulip/zulip style pull request template.
  .github/pull_request_template.md
Labels: size: M
